import{a as P,S as q,i as B}from"./assets/vendor-DgsA5abv.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const M="51362308-fccd9ac64991a037e5dade233",E="https://pixabay.com/api/";async function f(e,s=1){return(await P.get(E,{params:{key:M,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}})).data}const h=document.querySelector(".gallery"),d=document.querySelector(".loader"),m=document.querySelector(".load-more"),x=new q(".gallery a");function p(e){const s=e.map(({webformatURL:r,largeImageURL:a,tags:t,likes:o,views:i,comments:S,downloads:$})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img src="${r}" alt="${t}" loading="lazy" />
          <div class="info">
            <div class="info-item"><span class="label">Likes</span><span class="value">${o}</span></div>
            <div class="info-item"><span class="label">Views</span><span class="value">${i}</span></div>
            <div class="info-item"><span class="label">Comments</span><span class="value">${S}</span></div>
            <div class="info-item"><span class="label">Downloads</span><span class="value">${$}</span></div>
          </div>
        </a>
      </li>`).join("");h.insertAdjacentHTML("beforeend",s),x.refresh()}function A(){h.innerHTML=""}function y(){d.classList.add("is-visible"),d.classList.remove("is-hidden")}function g(){d.classList.remove("is-visible"),d.classList.add("is-hidden")}function v(){m.classList.remove("is-hidden")}function u(){m.classList.add("is-hidden")}const T="/goit-js-hw-12/assets/sprite-BWBAyIsh.svg",H=document.querySelector(".form"),O=document.querySelector('input[name="search-text"]'),_=document.querySelector(".load-more");let n=1,c="";const L=15;H.addEventListener("submit",async e=>{if(e.preventDefault(),c=O.value.trim(),n=1,!c){l("Please enter a search query!");return}A(),u(),y();try{const s=await f(c,n);if(s.hits.length===0){l("Sorry, there are no images matching your search query.");return}p(s.hits);const r=Math.ceil(s.totalHits/L);n<r?v():(u(),w("We're sorry, but you've reached the end of search results."))}catch{l("An error occurred. Please try again later.")}finally{g()}});_.addEventListener("click",async()=>{n++,y(),u();try{const e=await f(c,n);p(e.hits);const s=Math.ceil(e.totalHits/L);n>=s?(u(),w("We're sorry, but you've reached the end of search results.")):v(),G()}catch{l("Failed to load more images.")}finally{g()}});function b(e,s,r,a="info",t=""){B[a]({class:`custom-toast ${t}`.trim(),icon:"",message:`
      <svg class="toast-icon" width="24" height="24">
        <use xlink:href="${T}#${s}"></use>
      </svg>
      <span class="${r}">${e}</span>
    `,dangerouslyHTML:!0,position:"topRight",timeout:3e3})}function l(e){b(e,"icon-error","error-text","error")}function w(e){b(e,"icon-info","info-text","info","end-toast")}function G(){const e=document.querySelector(".gallery-item");if(!e)return;const{height:s}=e.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
